// =====================================================================
// jiaminglake.js
// All application logic for 2025 戒茂斯上嘉明湖四日縱走
// All data (waypoints, GPS track, elevation profile) comes from
// waypoint-data.js (generated by build.js from waypoint.json)
// =====================================================================

// ---- Globals filled by boot() ----
var WAYPOINTS       = [];
var WAYPOINT_PHOTOS = {};
var dayColors       = {};
var dayEmoji        = {};
var dayNames        = {};
var TOTAL_KM        = 0;
var SEGMENTS        = [];
var PROFILE_DATA    = [];
var SUPPLEMENT_LINES = [];

// ---- Map & chart state ----
var map;
var elevChart   = null;
var chartBuilt  = false;
var activeMarkers = [];
var activeCard  = null;

// ---- Photo modal state ----
var currentPhotos   = [];
var currentPhotoIdx = 0;
var currentWaypointName = '';
var currentWaypointOrder = null;
var editingPhotoSrc = null;

// 上傳／編輯／刪除彈窗都是對「目前照片彈窗裡正在看的那一張」操作
function getActivePhotos(){ return currentPhotos; }
function getActivePhotoIdx(){ return currentPhotoIdx; }
function getActiveWaypointName(){ return currentWaypointName; }
function getActiveWaypointOrder(){ return currentWaypointOrder; }

// ---- Day display order ----
var DAY_ORDER = ['D0','D1','D2','D3','D4'];

// ---- API base ----
// 本機用 node server.js（同 origin，走 8000 port）測試；
// 部署到 GitHub Pages 等靜態空間時，寫入類 API 一律改打這個 Cloudflare Worker
// （部署好 worker 後，把下面網址換成你自己的 *.workers.dev 網址）
var CLOUD_API_BASE = 'https://jiaminglake-api.tsungkailu.workers.dev';

function resolveApiUrl(path){
  if (window.location.port === '8000') {
    return path;
  }
  return CLOUD_API_BASE + path;
}

// ---- GitHub raw content：commit 一成功內容就能直接讀到，不必等 GitHub Pages 重新 build/deploy ----
var GITHUB_OWNER  = 'tsungkailu';
var GITHUB_REPO   = 'JiaMingLake';
var GITHUB_BRANCH = 'main';

function githubRawUrl(path, bust){
  var url = 'https://raw.githubusercontent.com/' + GITHUB_OWNER + '/' + GITHUB_REPO + '/' + GITHUB_BRANCH + '/' + path;
  if (bust) url += (url.indexOf('?') >= 0 ? '&' : '?') + 'v=' + bust;
  return url;
}

// ---- 本機「已存到 GitHub、但 Pages 可能還沒重新部署」的待確認變更佇列 ----
// GitHub Pages 從 commit 到網站真的重新部署完成常常要 30 秒以上；這段期間如果重新整理頁面，
// 會讀到還沒更新的 waypoint-data.js，讓剛存好的修改看起來「消失」。
// 這裡把每一筆已經成功 commit 的變更先存進 localStorage，boot() 時疊加在剛載入的資料上，
// 直到偵測到 bundled 資料已經跟上了才會把該筆記錄丟掉，避免佇列無限累積。
var LOCAL_PATCH_KEY = 'jiaminglake_pending_patches_v1';

function loadLocalPatches(){
  try { return JSON.parse(localStorage.getItem(LOCAL_PATCH_KEY) || '[]'); } catch(e){ return []; }
}
function saveLocalPatches(patches){
  try { localStorage.setItem(LOCAL_PATCH_KEY, JSON.stringify(patches)); } catch(e){}
}
function addLocalPatch(patch){
  var patches = loadLocalPatches();
  patches.push(patch);
  saveLocalPatches(patches);
}

function applyLocalPatches(){
  var patches = loadLocalPatches();
  if(!patches.length) return;
  var stillPending = [];
  patches.forEach(function(patch){
    if(!applyOnePatch(patch)) stillPending.push(patch);
  });
  saveLocalPatches(stillPending);
}

// 回傳 true 代表「bundled 資料已經跟這筆變更一致了」，可以把這筆記錄丟掉
function applyOnePatch(patch){
  if(patch.type === 'add-photo'){
    var list = WAYPOINT_PHOTOS[patch.order] || (WAYPOINT_PHOTOS[patch.order] = []);
    var alreadyLive = list.some(function(p){ return p._realSrc && p._realSrc === patch.photo._realSrc; });
    if(!alreadyLive) list.push(patch.photo);
    return alreadyLive;
  }
  if(patch.type === 'edit-photo'){
    var editList = WAYPOINT_PHOTOS[patch.order] || [];
    var photo = editList.filter(function(p){ return p._realSrc === patch.photoSrc; })[0];
    if(!photo) return true;
    var alreadyLive = photo.body === patch.body && (!patch.src || photo.src === patch.src);
    photo.body  = patch.body;
    if(patch.src) photo.src = patch.src;
    return alreadyLive;
  }
  if(patch.type === 'delete-photo'){
    var delList = WAYPOINT_PHOTOS[patch.order] || [];
    var idx = -1;
    for(var i=0;i<delList.length;i++){ if(delList[i]._realSrc === patch.photoSrc){ idx = i; break; } }
    if(idx < 0) return true;
    delList.splice(idx, 1);
    return false;
  }
  if(patch.type === 'update-waypoint'){
    var wp = null;
    for(var j=0;j<WAYPOINTS.length;j++){ if(WAYPOINTS[j].order === patch.order){ wp = WAYPOINTS[j]; break; } }
    if(!wp) return true;
    // 不含 desc：故事文字已改由照片說明承載，地標編輯不再碰它
    var mapped = {
      name: patch.fields.name,
      day:  patch.fields.day,
      time: patch.fields.time,
      km:   patch.fields.km,
      ele:  patch.fields.elevation
    };
    var wpAlreadyLive = Object.keys(mapped).every(function(k){ return wp[k] === mapped[k]; });
    Object.assign(wp, mapped);
    return wpAlreadyLive;
  }
  return true;
}

// 背景同步結果的提示（成功／失敗都會給明確回饋，讓使用者知道是不是「真的」存好了）
function showSyncToast(message, isError){
  var toast = document.createElement('div');
  toast.className = 'sync-error-toast' + (isError ? '' : ' success');
  toast.textContent = (isError ? '⚠️ ' : '✅ ') + message;
  var closeBtn = document.createElement('button');
  closeBtn.textContent = '✕';
  closeBtn.setAttribute('aria-label', '關閉提示');
  closeBtn.addEventListener('click', function(){ toast.remove(); });
  toast.appendChild(closeBtn);
  document.body.appendChild(toast);
  // 失敗訊息代表真的沒存到，山區訊號不穩時很容易錯過一閃即逝的提示，
  // 所以錯誤訊息留在畫面上直到使用者按關閉，成功訊息才自動消失。
  if(!isError){
    setTimeout(function(){ toast.remove(); }, 4000);
  }
}
function showSyncErrorToast(message){ showSyncToast(message, true); }
function showSyncSuccessToast(message){ showSyncToast(message, false); }

// =====================================================================
// BOOT
// =====================================================================
(function boot(){
  if(typeof WAYPOINT_DATA === 'undefined'){
    document.body.innerHTML =
      "<p style='padding:20px;color:red'>找不到 waypoint-data.js，請確認檔案與 jiaminglake.html 在同一資料夾，並執行 node build.js。</p>";
    return;
  }

  var data = WAYPOINT_DATA;
  var meta = data.meta;

  dayColors        = meta.dayColors;
  dayEmoji         = meta.dayEmoji;
  dayNames         = meta.dayNames;
  TOTAL_KM         = meta.totalKm;
  SEGMENTS         = data.gpsSegments  || [];
  PROFILE_DATA     = data.profileData  || [];
  SUPPLEMENT_LINES = data.supplementLines || [];

  // Build flat WAYPOINTS array and WAYPOINT_PHOTOS lookup
  data.waypoints.forEach(function(wp){
    WAYPOINTS.push({
      name:        wp.name,
      day:         wp.day,
      order:       wp.order  || 0,
      date:        wp.date   || '',
      time:        wp.time,
      km:          wp.km,
      ele:         wp.elevation,
      lat:         wp.lat,
      lng:         wp.lng,
      profile_km:  wp.profile_km,
      profile_ele: wp.profile_ele,
      desc:        wp.desc,
      spur:        wp.spur        || false,
      spurReturn:  wp.spurReturn  || false
    });
    WAYPOINT_PHOTOS[wp.order] = (wp.photos || []).map(function(p){
      // _realSrc：這張照片在 repo 裡實際的檔案路徑，用來識別「編輯/刪除哪一張」。
      // 剛上傳、還在背景同步中的照片，_realSrc 會是 null，代表還不能編輯/刪除。
      return { src: p.src || '', title: p.title || '', body: p.body || '', _realSrc: p.src || '' };
    });
  });

  // 疊加「已經存到 GitHub、但 waypoint-data.js 這份 bundled 資料可能還沒跟上」的本機待確認變更，
  // 讓剛存好的照片/地標修改重新整理後也看得到，不必等 GitHub Pages 重新部署完成。
  applyLocalPatches();

  // Sort WAYPOINTS chronologically by day and order
  WAYPOINTS.sort(function(a, b){
    var di = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
    return di !== 0 ? di : (a.order || 0) - (b.order || 0);
  });

  // Boot
  initMap();
  initPhotoModal();
})();

// =====================================================================
// MAP
// =====================================================================
function initMap(){
  map = L.map('map', {zoomControl: true}).setView([23.265, 121.010], 12);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '© OpenStreetMap contributors'
  }).addTo(map);

  // ── GPS 實際軌跡（上/下坡雙色）──────────────────────────────────────
  SEGMENTS.forEach(function(seg){
    var dEle  = seg.ee - seg.es;
    var color = dEle >= 0 ? '#c0392b' : '#1565c0';
    L.polyline(seg.c, {color: color, weight: 4, opacity: 0.88})
      .bindPopup(
        '<b>' + seg.d + ' 路段</b><br>' +
        '起點：' + seg.es + 'm　終點：' + seg.ee + 'm<br>' +
        '高差：<b>' + (dEle >= 0 ? '+' : '') + dEle + 'm</b><br>' +
        '<span style="color:' + color + ';font-weight:700">' +
        (dEle >= 0 ? '▲ 上坡' : '▼ 下坡') + '</span>'
      )
      .addTo(map);
  });

  // ── 補線（無 GPS 覆蓋的路段）──────────────────────────────────────
  SUPPLEMENT_LINES.forEach(function(line){
    var color   = dayColors[line.day] || '#888';
    var options = {
      color:   color,
      weight:  3,
      opacity: 0.85
    };
    if(line.dashed){
      options.dashArray = '8, 6';
      options.weight    = 2.5;
    }
    var popup = line.label
      ? '<b>' + line.label + '</b><br><span style="color:#888;font-size:.85em">標記點連線（無 GPS 軌跡）</span>'
      : '標記點連線（無 GPS 軌跡）';
    L.polyline(line.coords, options).bindPopup(popup).addTo(map);
  });

  // ── 地標標記 ─────────────────────────────────────────────────────
  WAYPOINTS.forEach(function(wp){
    if (wp.lat === null || wp.lng === null || wp.lat === undefined || wp.lng === undefined) {
      return;
    }
    var color = dayColors[wp.day];
    var icon  = L.divIcon({
      className: '',
      html:
        "<div style='width:28px;height:28px;border-radius:50%;background:" + color +
        ";border:2px solid #fff;display:flex;align-items:center;justify-content:center;" +
        "color:#fff;font-size:.6rem;font-weight:700;box-shadow:0 2px 6px rgba(0,0,0,.4)'>" +
        wp.day + '</div>',
      iconSize: [28, 28], iconAnchor: [14, 14], popupAnchor: [0, -16]
    });
    var m = L.marker([wp.lat, wp.lng], {icon: icon, draggable: true}).addTo(map);
    (function(wp, marker){
      marker.on('click', function(){
        openPhotoModal(wp);
      });
      
      marker.on('dragend', function(event){
        var position = event.target.getLatLng();
        var newLat = position.lat;
        var newLng = position.lng;
        
        // 儲存目前地圖中心點與縮放大小，以便重載後恢復
        sessionStorage.setItem('mapCenter', JSON.stringify(map.getCenter()));
        sessionStorage.setItem('mapZoom', map.getZoom());
        
        updateWaypointCoords(wp.name, wp.order, newLat, newLng);
      });
    })(wp, m);
  });

  // Fix Leaflet popup close button
  map.on('popupopen', function(){
    document.querySelectorAll('.leaflet-popup-close-button').forEach(function(btn){
      btn.removeAttribute('href');
      btn.style.cursor = 'pointer';
    });
  });

  // ── 恢復地圖定位或自動縮放至 GPS 軌跡範圍 ──────────────────────────
  var savedCenter = sessionStorage.getItem('mapCenter');
  var savedZoom   = sessionStorage.getItem('mapZoom');
  if(savedCenter && savedZoom){
    var center = JSON.parse(savedCenter);
    map.setView([center.lat, center.lng], parseInt(savedZoom));
    sessionStorage.removeItem('mapCenter');
    sessionStorage.removeItem('mapZoom');
  } else if(SEGMENTS.length > 0){
    var allLats = SEGMENTS.reduce(function(a,s){ return a.concat(s.c.map(function(p){ return p[0]; })); }, []);
    var allLngs = SEGMENTS.reduce(function(a,s){ return a.concat(s.c.map(function(p){ return p[1]; })); }, []);
    map.fitBounds([
      [Math.min.apply(null, allLats), Math.min.apply(null, allLngs)],
      [Math.max.apply(null, allLats), Math.max.apply(null, allLngs)]
    ], {padding: [40, 40]});
  }
}

// =====================================================================
// ELEVATION CHART
// =====================================================================
function buildChart(){
  if(chartBuilt) return;
  chartBuilt = true;
  var ctx = document.getElementById('elev-chart').getContext('2d');
  elevChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels:   PROFILE_DATA.map(function(p){ return p[0]; }),
      datasets: [{
        label:           '海拔',
        data:            PROFILE_DATA.map(function(p){ return p[1]; }),
        fill:            true,
        backgroundColor: 'rgba(45,90,61,.15)',
        borderColor:     '#2d5a3d',
        borderWidth:     1.5,
        pointRadius:     0,
        tension:         .3
      }]
    },
    options: {
      responsive:          true,
      maintainAspectRatio: false,
      animation:           {duration: 400},
      plugins: {
        legend:  {display: false},
        tooltip: {
          mode: 'index', intersect: false,
          callbacks: {
            title: function(i){ return i[0].parsed.x.toFixed(2) + 'km'; },
            label: function(c){ return ' ' + c.parsed.y.toFixed(0) + 'm'; }
          }
        }
      },
      // 這張圖是彈窗裡的輔助資訊，軸標題拿掉、刻度縮到最小，把空間讓給曲線本身
      layout: {padding: {top: 6, right: 2, bottom: 0, left: 0}},
      scales: {
        x: {
          type: 'linear', min: 0, max: TOTAL_KM,
          grid: {display: false},
          border: {color: '#e2e8f0'},
          ticks: {
            maxTicksLimit: 6,
            font: {size: 9},
            color: '#9aa5ad',
            padding: 2,
            callback: function(v){ return v.toFixed(0) + 'k'; }
          }
        },
        y: {
          grid: {color: '#f1f5f4'},
          border: {display: false},
          ticks: {
            maxTicksLimit: 4,
            font: {size: 9},
            color: '#9aa5ad',
            padding: 4,
            callback: function(v){ return v + 'm'; }
          }
        }
      }
    }
  });
}

function kmToPixel(km){
  if(!elevChart) return null;
  return elevChart.scales.x.getPixelForValue(km);
}
function eleToPixel(ele){
  if(!elevChart) return null;
  return elevChart.scales.y.getPixelForValue(ele);
}

function redrawOverlay(){
  var svg = document.getElementById('chart-overlay');
  while(svg.firstChild) svg.removeChild(svg.firstChild);
  if(!elevChart || !chartBuilt) return;

  var ca = elevChart.chartArea;
  activeMarkers.forEach(function(item){
    var wp    = item.wp;
    var color = dayColors[wp.day];
    var x     = kmToPixel(wp.profile_km);
    var y     = eleToPixel(wp.profile_ele);
    if(x == null) return;

    // Vertical dashed line
    var line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
    line.setAttribute('x1', x);    line.setAttribute('y1', ca.top);
    line.setAttribute('x2', x);    line.setAttribute('y2', ca.bottom);
    line.setAttribute('stroke', color);
    line.setAttribute('stroke-width', '1.5');
    line.setAttribute('stroke-dasharray', '4,3');
    line.setAttribute('opacity', '0.85');
    svg.appendChild(line);

    // Dot on curve
    if(y != null){
      var circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      circle.setAttribute('cx', x);  circle.setAttribute('cy', y);
      circle.setAttribute('r', '5');
      circle.setAttribute('fill', color);
      circle.setAttribute('stroke', '#fff');
      circle.setAttribute('stroke-width', '2');
      svg.appendChild(circle);
    }

    // 地標名稱不再標在圖上：彈窗標題已經寫得很清楚了，圖上再寫一次只會變得雜亂
  });
}

// 在高度剖面圖上標出目前正在看的那一個地標 (彈窗一次只看一個點，所以只留一個標記)
function showChartMarker(wp){
  buildChart();
  activeMarkers = [{wp: wp}];
  // 圖表要等彈窗顯示出來才量得到實際寬高，這裡補一次 resize 才不會畫成 0 寬
  if(elevChart) elevChart.resize();
  requestAnimationFrame(redrawOverlay);
}

window.addEventListener('resize', function(){
  requestAnimationFrame(redrawOverlay);
});

// =====================================================================
// PHOTO MODAL
// =====================================================================
// 將圖片檔案壓縮並轉換為 WebP 格式的 Base64 (寬或高最大 1200px，畫質 0.82)
function compressImageToWebp(file, callback){
  var reader = new FileReader();
  reader.onload = function(e){
    compressDataUrlToWebp(e.target.result, callback);
  };
  reader.readAsDataURL(file);
}

// 部分瀏覽器 (例如較舊的 Safari) 的 canvas 不支援輸出 webp，toDataURL 會自動退回輸出 png，
// 這裡從實際產生的 data URL 判斷副檔名，讓伺服器存檔時用對的副檔名，避免內容跟副檔名對不上。
function extFromDataUrl(dataUrl){
  var m = dataUrl.match(/^data:image\/([a-zA-Z0-9.+-]+);base64,/);
  if(!m) return 'webp';
  var type = m[1].toLowerCase();
  if(type === 'jpeg') return 'jpg';
  return /^[a-z0-9]+$/.test(type) ? type : 'webp';
}

// 與上面共用的核心壓縮邏輯，輸入直接是圖片的 data URL (例如從雲端硬碟下載後取得的圖片)
// callback(dataUrl, ext)：ext 是實際輸出格式的副檔名 (通常是 webp，不支援時會是 png)
function compressDataUrlToWebp(dataUrl, callback){
  var img = new Image();
  img.onload = function(){
    var maxDim = 1200;
    var width = img.width;
    var height = img.height;
    if(width > maxDim || height > maxDim){
      if(width > height){
        height = Math.round((height * maxDim) / width);
        width = maxDim;
      } else {
        width = Math.round((width * maxDim) / height);
        height = maxDim;
      }
    }

    var canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0, width, height);

    var outDataUrl = canvas.toDataURL('image/webp', 0.82);
    callback(outDataUrl, extFromDataUrl(outDataUrl));
  };
  img.src = dataUrl;
}

// 請伺服器下載一個公開的 Google Drive 檔案分享連結，回傳圖片的 data URL。
// Worker 會直接把圖片位元組串流回來（成功時 Content-Type 是 image/*），
// 失敗時才會是一段 JSON 錯誤訊息。
function fetchDriveImageAsDataUrl(driveUrl, onSuccess, onError){
  var apiUrl = resolveApiUrl('/api/fetch-drive-image');
  fetch(apiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: driveUrl })
  })
  .then(function(res){
    var contentType = res.headers.get('content-type') || '';
    if (!res.ok || contentType.indexOf('application/json') === 0) {
      return res.json().then(function(errRes){
        throw new Error(errRes.error || ('HTTP ' + res.status));
      });
    }
    return res.blob();
  })
  .then(function(blob){
    var reader = new FileReader();
    reader.onload = function(e){ onSuccess(e.target.result); };
    reader.onerror = function(){ onError('讀取圖片資料失敗'); };
    reader.readAsDataURL(blob);
  })
  .catch(function(err){ onError(err.message || String(err)); });
}

function resetUploadForm(){
  document.getElementById('upload-image').value = '';
  document.getElementById('upload-drive-url').value = '';
  document.getElementById('upload-body').value = '';
  document.getElementById('upload-status').textContent = '';
  document.getElementById('upload-status').className = 'upload-status';
}

function initPhotoModal(){
  var photoModal = document.getElementById('photo-modal');
  var uploadModal = document.getElementById('upload-modal');

  // 主彈窗關閉按鈕
  document.getElementById('photo-modal-close').addEventListener('click', function(){
    photoModal.classList.remove('open');
  });
  photoModal.addEventListener('click', function(e){
    if(e.target === photoModal) photoModal.classList.remove('open');
  });

  // 新增照片彈窗控制
  var btnOpenUpload = document.getElementById('btn-open-upload-modal');
  if (btnOpenUpload) {
    btnOpenUpload.addEventListener('click', function(){
      resetUploadForm();
      uploadModal.classList.add('open');
    });
  }
  var btnCloseUpload = document.getElementById('upload-modal-close');
  if (btnCloseUpload) {
    btnCloseUpload.addEventListener('click', function(){
      uploadModal.classList.remove('open');
    });
  }
  uploadModal.addEventListener('click', function(e){
    if(e.target === uploadModal) uploadModal.classList.remove('open');
  });

  // 編輯地標彈窗控制
  var editModal = document.getElementById('edit-modal');
  var btnOpenEdit = document.getElementById('btn-open-edit-modal');
  if (btnOpenEdit) {
    btnOpenEdit.addEventListener('click', function(){
      var wp = WAYPOINTS.find(function(w){ return w.order === currentWaypointOrder; });
      if(!wp) return;
      document.getElementById('edit-name').value      = wp.name;
      document.getElementById('edit-day').value       = wp.day;
      document.getElementById('edit-time').value      = wp.time;
      document.getElementById('edit-km').value        = wp.km;
      document.getElementById('edit-elevation').value = wp.ele;
      document.getElementById('edit-status').textContent = '';
      document.getElementById('edit-status').className  = 'upload-status';
      editModal.classList.add('open');
    });
  }
  var btnCloseEdit = document.getElementById('edit-modal-close');
  if (btnCloseEdit) {
    btnCloseEdit.addEventListener('click', function(){
      editModal.classList.remove('open');
    });
  }
  editModal.addEventListener('click', function(e){
    if(e.target === editModal) editModal.classList.remove('open');
  });

  // 編輯照片彈窗控制
  var editPhotoModal = document.getElementById('edit-photo-modal');
  function openEditPhotoModal(){
    var photo = getActivePhotos()[getActivePhotoIdx()];
    if(!photo) return;
    if(!photo._realSrc){
      alert('這張照片還在同步到 GitHub 中，請稍等一下再編輯。');
      return;
    }
    editingPhotoSrc = photo._realSrc;
    document.getElementById('edit-photo-image').value = '';
    document.getElementById('edit-photo-drive-url').value = '';
    document.getElementById('edit-photo-body').value  = photo.body  || '';
    document.getElementById('edit-photo-status').textContent = '';
    document.getElementById('edit-photo-status').className  = 'upload-status';
    editPhotoModal.classList.add('open');
  }
  var btnOpenEditPhoto = document.getElementById('photo-modal-edit-btn');
  if (btnOpenEditPhoto) {
    btnOpenEditPhoto.addEventListener('click', function(){ openEditPhotoModal(); });
  }
  var btnCloseEditPhoto = document.getElementById('edit-photo-modal-close');
  if (btnCloseEditPhoto) {
    btnCloseEditPhoto.addEventListener('click', function(){
      editPhotoModal.classList.remove('open');
    });
  }
  editPhotoModal.addEventListener('click', function(e){
    if(e.target === editPhotoModal) editPhotoModal.classList.remove('open');
  });

  // 上一張 / 下一張照片：走完目前地標的照片後會自動接到相鄰的地標
  // 標題下方的大按鈕與照片上的左右箭頭走同一套邏輯
  document.getElementById('wp-nav-prev').addEventListener('click', function(){ gotoPhotoStep(-1); });
  document.getElementById('wp-nav-next').addEventListener('click', function(){ gotoPhotoStep(1); });
  document.getElementById('photo-prev').addEventListener('click', function(){ gotoPhotoStep(-1); });
  document.getElementById('photo-next').addEventListener('click', function(){ gotoPhotoStep(1); });
  document.addEventListener('keydown', function(e){
    if(uploadModal.classList.contains('open')) {
      if(e.key === 'Escape') uploadModal.classList.remove('open');
      return;
    }
    if(editModal.classList.contains('open')) {
      if(e.key === 'Escape') editModal.classList.remove('open');
      return;
    }
    if(editPhotoModal.classList.contains('open')) {
      if(e.key === 'Escape') editPhotoModal.classList.remove('open');
      return;
    }
    if(!photoModal.classList.contains('open')) return;
    if(e.key === 'ArrowLeft')  document.getElementById('photo-prev').click();
    if(e.key === 'ArrowRight') document.getElementById('photo-next').click();
    if(e.key === 'Escape')     photoModal.classList.remove('open');
  });

  // ── 照片上傳與 Canvas WebP 壓縮邏輯 ──────────────────────────────
  var btnSubmit = document.getElementById('upload-submit');
  var fileInput = document.getElementById('upload-image');
  var statusEl  = document.getElementById('upload-status');

  if (btnSubmit) {
    btnSubmit.addEventListener('click', function(){
      var file     = fileInput.files[0];
      var driveUrl = document.getElementById('upload-drive-url').value.trim();

      if(!file && !driveUrl){
        statusEl.textContent = '❌ 請選擇一張照片，或貼上 Google Drive 分享連結';
        statusEl.className = 'upload-status error';
        return;
      }
      if(!getActiveWaypointName()){
        statusEl.textContent = '❌ 無法辨識當前地標';
        statusEl.className = 'upload-status error';
        return;
      }

      function proceedWithDataUrl(dataUrl){
        statusEl.textContent = '⏳ 正在壓縮圖片中...';
        statusEl.className = 'upload-status';

        compressDataUrlToWebp(dataUrl, function(webpBase64, ext){
          var bodyVal  = document.getElementById('upload-body').value.trim();
          var waypointName  = getActiveWaypointName();
          var waypointOrder = getActiveWaypointOrder();

          // ── Optimistic UI：不等雲端同步，先把照片加進本地資料立刻顯示 ──
          var newPhoto = { src: webpBase64, title: '', body: bodyVal, _realSrc: null };
          if (!WAYPOINT_PHOTOS[waypointOrder]) WAYPOINT_PHOTOS[waypointOrder] = [];
          WAYPOINT_PHOTOS[waypointOrder].push(newPhoto);
          refreshActivePhotoView(WAYPOINT_PHOTOS[waypointOrder].length - 1);

          statusEl.textContent = '✅ 已顯示在畫面上！背景同步到 GitHub 中...';
          statusEl.className = 'upload-status success';
          setTimeout(function(){
            uploadModal.classList.remove('open');
          }, 600);

          var uploadUrl = resolveApiUrl('/api/upload');

          fetch(uploadUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              waypointName: waypointName,
              waypointOrder: waypointOrder,
              body: bodyVal,
              image: webpBase64,
              ext: ext
            })
          })
          .then(function(res){ return res.json(); })
          .then(function(res){
            if(res.success){
              newPhoto._realSrc = res.src;
              newPhoto.src = githubRawUrl(res.src, Date.now());
              addLocalPatch({
                type: 'add-photo',
                order: waypointOrder,
                photo: { src: newPhoto.src, title: newPhoto.title, body: newPhoto.body, _realSrc: newPhoto._realSrc }
              });
              showSyncSuccessToast('照片已確實存檔到 GitHub，重新整理也看得到');
            } else {
              showSyncErrorToast('照片同步到 GitHub 失敗（畫面上仍看得到，但重新整理後會消失）: ' + res.error);
            }
          })
          .catch(function(err){
            showSyncErrorToast('照片同步到 GitHub 失敗（畫面上仍看得到，但重新整理後會消失）: ' + err);
          });
        });
      }

      if(file){
        var reader = new FileReader();
        reader.onload = function(e){ proceedWithDataUrl(e.target.result); };
        reader.readAsDataURL(file);
        return;
      }

      statusEl.textContent = '⏳ 正在從 Google Drive 下載圖片...';
      statusEl.className = 'upload-status';
      fetchDriveImageAsDataUrl(driveUrl, proceedWithDataUrl, function(err){
        statusEl.textContent = '❌ 下載失敗: ' + err;
        statusEl.className = 'upload-status error';
      });
    });
  }

  // ── 照片刪除邏輯 (照片彈窗、高度剖面照片區共用) ────────────────────
  function deleteActivePhoto(){
    var photos = getActivePhotos();
    var idx = getActivePhotoIdx();
    var photo = photos[idx];
    if (!photo) return;

    if (!photo._realSrc) {
      alert('這張照片還在同步到 GitHub 中，請稍等一下再刪除。');
      return;
    }

    var isConfirmed = confirm("確定要刪除這張照片嗎？\n這將會從檔案庫中永久刪除此照片且無法復原！");
    if (!isConfirmed) return;

    // ── Optimistic UI：不等雲端同步，先從畫面上移除 ──
    var waypointName  = getActiveWaypointName();
    var waypointOrder = getActiveWaypointOrder();
    var photoSrc = photo._realSrc;
    photos.splice(idx, 1);
    refreshActivePhotoView(idx);

    var deleteUrl = resolveApiUrl('/api/delete-photo');

    fetch(deleteUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        waypointName: waypointName,
        waypointOrder: waypointOrder,
        photoSrc: photoSrc
      })
    })
    .then(function(res){ return res.json(); })
    .then(function(res){
      if(res.success){
        addLocalPatch({ type: 'delete-photo', order: waypointOrder, photoSrc: photoSrc });
        showSyncSuccessToast('刪除已確實同步到 GitHub');
      } else {
        showSyncErrorToast('刪除同步到 GitHub 失敗: ' + res.error);
      }
    })
    .catch(function(err){
      showSyncErrorToast('刪除同步到 GitHub 失敗: ' + err);
    });
  }

  var btnDelete = document.getElementById('photo-modal-delete-btn');
  if (btnDelete) {
    btnDelete.addEventListener('click', function(){
      deleteActivePhoto();
    });
  }

  // ── 地標編輯邏輯 ─────────────────────────────────────────────────
  var btnEditSubmit = document.getElementById('edit-submit');
  if (btnEditSubmit) {
    btnEditSubmit.addEventListener('click', function(){
      var statusEl = document.getElementById('edit-status');
      var nameVal = document.getElementById('edit-name').value.trim();
      var dayVal  = document.getElementById('edit-day').value;
      var timeVal = document.getElementById('edit-time').value.trim();
      var kmVal   = document.getElementById('edit-km').value.trim();
      var eleVal  = document.getElementById('edit-elevation').value.trim();

      if(!nameVal || !timeVal || !kmVal || !eleVal){
        statusEl.textContent = '❌ 請完整填寫所有欄位';
        statusEl.className = 'upload-status error';
        return;
      }

      statusEl.textContent = '⏳ 正在儲存修改...';
      statusEl.className = 'upload-status';

      var updateUrl = resolveApiUrl('/api/update-waypoint');

      fetch(updateUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          waypointOrder: currentWaypointOrder,
          name: nameVal,
          day: dayVal,
          time: timeVal,
          km: kmVal,
          elevation: eleVal
        })
      })
      .then(function(res){ return res.json(); })
      .then(function(res){
        if(res.success){
          // 先把這次修改記錄下來，reload 後即使 GitHub Pages 還沒重新部署，
          // boot() 也會疊加這筆記錄，讓修改不會「看起來消失」。
          addLocalPatch({
            type: 'update-waypoint',
            order: currentWaypointOrder,
            fields: { name: nameVal, day: dayVal, time: timeVal, km: kmVal, elevation: eleVal }
          });
          statusEl.textContent = '🎉 更新成功！已確實存檔，網頁即將重新整理...';
          statusEl.className = 'upload-status success';
          setTimeout(function(){
            window.location.reload();
          }, 1000);
        } else {
          statusEl.textContent = '❌ 更新失敗: ' + res.error;
          statusEl.className = 'upload-status error';
        }
      })
      .catch(function(err){
        statusEl.textContent = '❌ 連線伺服器失敗: ' + err;
        statusEl.className = 'upload-status error';
      });
    });
  }

  // ── 照片編輯邏輯 ─────────────────────────────────────────────────
  var btnEditPhotoSubmit = document.getElementById('edit-photo-submit');
  if (btnEditPhotoSubmit) {
    btnEditPhotoSubmit.addEventListener('click', function(){
      var statusEl   = document.getElementById('edit-photo-status');
      var fileInput  = document.getElementById('edit-photo-image');
      var driveUrl   = document.getElementById('edit-photo-drive-url').value.trim();
      var bodyVal    = document.getElementById('edit-photo-body').value.trim();
      var file       = fileInput.files[0];

      function sendPhotoUpdate(webpBase64){
        var photos = getActivePhotos();
        var photo = photos.find(function(p){ return p._realSrc === editingPhotoSrc; });
        if(!photo) return;

        // ── Optimistic UI：不等雲端同步，先套用修改立刻顯示 ──
        photo.body  = bodyVal;
        if (webpBase64) photo.src = webpBase64;
        refreshActivePhotoView(photos.indexOf(photo));

        statusEl.textContent = '✅ 已套用修改！背景同步到 GitHub 中...';
        statusEl.className = 'upload-status success';
        setTimeout(function(){
          editPhotoModal.classList.remove('open');
        }, 600);

        var updateUrl = resolveApiUrl('/api/update-photo');

        var payload = {
          waypointName: getActiveWaypointName(),
          waypointOrder: getActiveWaypointOrder(),
          photoSrc: editingPhotoSrc,
          body: bodyVal
        };
        if (webpBase64) payload.image = webpBase64;

        fetch(updateUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        })
        .then(function(res){ return res.json(); })
        .then(function(res){
          if(res.success){
            // 檔案路徑跟原本一樣（沒有改檔名），加上時間戳避免瀏覽器快取到換圖前的舊內容
            var newSrc = webpBase64 ? githubRawUrl(editingPhotoSrc, Date.now()) : photo.src;
            photo.src = newSrc;
            addLocalPatch({
              type: 'edit-photo',
              order: getActiveWaypointOrder(),
              photoSrc: editingPhotoSrc,
              body: bodyVal,
              src: webpBase64 ? newSrc : null
            });
            showSyncSuccessToast('照片編輯已確實同步到 GitHub');
          } else {
            showSyncErrorToast('照片編輯同步到 GitHub 失敗: ' + res.error);
          }
        })
        .catch(function(err){
          showSyncErrorToast('照片編輯同步到 GitHub 失敗: ' + err);
        });
      }

      if(file){
        var reader = new FileReader();
        reader.onload = function(e){
          statusEl.textContent = '⏳ 正在壓縮圖片中...';
          statusEl.className = 'upload-status';
          compressDataUrlToWebp(e.target.result, sendPhotoUpdate);
        };
        reader.readAsDataURL(file);
        return;
      }

      if(driveUrl){
        statusEl.textContent = '⏳ 正在從 Google Drive 下載圖片...';
        statusEl.className = 'upload-status';
        fetchDriveImageAsDataUrl(driveUrl, function(dataUrl){
          statusEl.textContent = '⏳ 正在壓縮圖片中...';
          compressDataUrlToWebp(dataUrl, sendPhotoUpdate);
        }, function(err){
          statusEl.textContent = '❌ 下載失敗: ' + err;
          statusEl.className = 'upload-status error';
        });
        return;
      }

      sendPhotoUpdate(null);
    });
  }
}

function openPhotoModal(wp, startIdx){
  var photos = WAYPOINT_PHOTOS[wp.order] || [];
  currentPhotos   = photos;
  currentPhotoIdx = Math.max(0, Math.min(startIdx || 0, Math.max(0, photos.length - 1)));
  currentWaypointName = wp.name;
  currentWaypointOrder = wp.order;

  resetUploadForm();

  // 重設置頂滾動條
  var scrollEl = document.getElementById('photo-modal-scrollable');
  if (scrollEl) scrollEl.scrollTop = 0;

  var photoModal = document.getElementById('photo-modal');

  // 標題：天數色票 + 地標名稱
  var titleEl = document.getElementById('photo-modal-title');
  titleEl.innerHTML = '';
  var badge = document.createElement('span');
  badge.className = 'wp-day-badge';
  badge.style.background = dayColors[wp.day] || 'var(--muted)';
  badge.textContent = wp.day;
  var nameEl = document.createElement('span');
  nameEl.textContent = wp.name;
  titleEl.appendChild(badge);
  titleEl.appendChild(nameEl);

  // 距離／時間／海拔：與下方的高度剖面圖同屬一塊資訊面板
  var metaEl = document.getElementById('photo-modal-meta');
  metaEl.innerHTML = '';
  appendStat(metaEl, '距離', wp.km);
  appendStat(metaEl, '時間', wp.time);
  appendStat(metaEl, '海拔', wp.ele);

  document.getElementById('photo-modal-desc').textContent = wp.desc || '';

  if(photos.length === 0){
    showEmptyPhotoModal();
  } else {
    renderPhoto();
  }
  photoModal.classList.add('open');

  // 高度剖面圖要等彈窗真的顯示出來 (量得到寬高) 才建得起來，所以放在下一個影格
  requestAnimationFrame(function(){ showChartMarker(wp); });
}

// 資訊面板裡的一組「標籤 + 數值」
function appendStat(container, label, value){
  var stat = document.createElement('div');
  stat.className = 'wp-stat';
  var labelEl = document.createElement('span');
  labelEl.className = 'wp-stat-label';
  labelEl.textContent = label;
  var valueEl = document.createElement('span');
  valueEl.className = 'wp-stat-value';
  valueEl.textContent = value || '—';
  stat.appendChild(labelEl);
  stat.appendChild(valueEl);
  container.appendChild(stat);
}

function showEmptyPhotoModal(){
  document.getElementById('photo-modal-delete-btn').style.display = 'none';
  document.getElementById('photo-modal-edit-btn').style.display   = 'none';
  document.getElementById('photo-modal-img').src        = '';
  document.getElementById('photo-modal-img').alt        = '暫無照片';
  document.getElementById('photo-modal-dots').innerHTML  = '';
  document.getElementById('photo-modal-photo-body').textContent  = '請點擊下方按鈕新增照片至此地標。';
  updatePhotoNav();
}

// Optimistic UI：新增/編輯/刪除照片後，立刻用目前 WAYPOINT_PHOTOS 的內容重繪
// 照片彈窗，不必等雲端同步、不必整頁重新整理
function refreshActivePhotoView(targetIdx){
  currentPhotos = WAYPOINT_PHOTOS[currentWaypointOrder] || [];
  if (currentPhotos.length === 0) { showEmptyPhotoModal(); return; }
  currentPhotoIdx = Math.max(0, Math.min(targetIdx, currentPhotos.length - 1));
  renderPhoto();
}

function renderPhoto(){
  var p = currentPhotos[currentPhotoIdx];
  document.getElementById('photo-modal-delete-btn').style.display = 'flex';
  document.getElementById('photo-modal-edit-btn').style.display   = 'flex';
  document.getElementById('photo-modal-img').src   = p.src;
  document.getElementById('photo-modal-img').alt   = p.title || '';
  document.getElementById('photo-modal-photo-body').textContent  = p.body  || '';

  var dotsEl = document.getElementById('photo-modal-dots');
  dotsEl.innerHTML = '';
  currentPhotos.forEach(function(_, idx){
    var dot = document.createElement('div');
    dot.className = 'photo-dot' + (idx === currentPhotoIdx ? ' active' : '');
    dot.addEventListener('click', function(){ currentPhotoIdx = idx; renderPhoto(); });
    dotsEl.appendChild(dot);
  });

  updatePhotoNav();
}

// =====================================================================
// 照片瀏覽：把所有地標的照片攤平成一條連續的序列，
// 「上一張／下一張」走完目前地標的照片後就會自動接到下一個地標
// =====================================================================
function buildPhotoSequence(){
  var seq = [];
  WAYPOINTS.forEach(function(wp){
    var photos = WAYPOINT_PHOTOS[wp.order] || [];
    if(photos.length === 0){
      // 還沒有照片的地標也留一個位置，才不會在瀏覽時被跳過而永遠到不了
      seq.push({ order: wp.order, idx: 0 });
      return;
    }
    photos.forEach(function(_, idx){ seq.push({ order: wp.order, idx: idx }); });
  });
  return seq;
}

function currentPhotoSeqPos(seq){
  for(var i = 0; i < seq.length; i++){
    if(seq[i].order === currentWaypointOrder && seq[i].idx === currentPhotoIdx) return i;
  }
  return -1;
}

function gotoPhotoStep(step){
  var seq = buildPhotoSequence();
  var pos = currentPhotoSeqPos(seq);
  if(pos < 0) return;
  var target = seq[pos + step];
  if(!target) return; // 已經是第一張／最後一張，不循環

  if(target.order === currentWaypointOrder){
    currentPhotoIdx = target.idx;
    renderPhoto();
    return;
  }
  var wp = WAYPOINTS.find(function(w){ return w.order === target.order; });
  if(wp) openPhotoModal(wp, target.idx);
}

// 依照目前位在整條照片序列的哪裡，更新導覽鈕與照片左右箭頭的可用狀態
function updatePhotoNav(){
  var seq = buildPhotoSequence();
  var pos = currentPhotoSeqPos(seq);
  var hasPrev = pos > 0;
  var hasNext = pos >= 0 && pos < seq.length - 1;

  var prevBtn = document.getElementById('wp-nav-prev');
  var nextBtn = document.getElementById('wp-nav-next');
  if(prevBtn) prevBtn.disabled = !hasPrev;
  if(nextBtn) nextBtn.disabled = !hasNext;

  document.getElementById('photo-prev').style.display = hasPrev ? 'flex' : 'none';
  document.getElementById('photo-next').style.display = hasNext ? 'flex' : 'none';
}

// ── 更新地標座標之 API 請求 ─────────────────────────────────────────
function updateWaypointCoords(name, order, lat, lng) {
  var updateUrl = resolveApiUrl('/api/update-coords');

  fetch(updateUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      waypointName: name,
      waypointOrder: order,
      lat: lat,
      lng: lng
    })
  })
  .then(function(res){ return res.json(); })
  .then(function(res){
    if(res.success){
      console.log('Coordinates updated successfully for: ' + name);
      window.location.reload();
    } else {
      alert('❌ 更新座標失敗: ' + res.error);
    }
  })
  .catch(function(err){
    alert('❌ 連線伺服器失敗: ' + err);
  });
}
