// =====================================================================
// jiaminglake.js
// All application logic for 2025 戒茂斯上嘉明湖四日縱走
// All data (waypoints, GPS track, elevation profile) comes from
// waypoint-data.js (generated by build.js from waypoint.json)
// =====================================================================

// ---- Globals filled by boot() ----
var WAYPOINTS       = [];
var WAYPOINT_PHOTOS = {};
var dayColors       = {};
var dayEmoji        = {};
var dayNames        = {};
var TOTAL_KM        = 0;
var SEGMENTS        = [];
var PROFILE_DATA    = [];
var SUPPLEMENT_LINES = [];

// ---- Map & chart state ----
var map;
var elevChart   = null;
var chartBuilt  = false;
var activeMarkers = [];
var activeCard  = null;

// ---- Photo modal state ----
var currentPhotos   = [];
var currentPhotoIdx = 0;
var currentWaypointName = '';
var currentWaypointOrder = null;
var editingPhotoSrc = null;

// ---- Elevation popup's own (independent) photo section state ----
var currentElevPhotos = [];
var currentElevPhotoIdx = 0;
var currentElevWaypointName = '';
var currentElevWaypointOrder = null;

// 上傳／編輯／刪除三個共用彈窗，依目前是被「照片彈窗」還是「高度剖面照片區」開啟而定
var activePhotoSource = 'modal'; // 'modal' | 'elev'
function getActivePhotos(){
  return activePhotoSource === 'elev' ? currentElevPhotos : currentPhotos;
}
function getActivePhotoIdx(){
  return activePhotoSource === 'elev' ? currentElevPhotoIdx : currentPhotoIdx;
}
function getActiveWaypointName(){
  return activePhotoSource === 'elev' ? currentElevWaypointName : currentWaypointName;
}
function getActiveWaypointOrder(){
  return activePhotoSource === 'elev' ? currentElevWaypointOrder : currentWaypointOrder;
}

// ---- Day display order ----
var DAY_ORDER = ['D0','D1','D2','D3','D4'];

// ---- API base ----
// 本機用 node server.js（同 origin，走 8000 port）測試；
// 部署到 GitHub Pages 等靜態空間時，寫入類 API 一律改打這個 Cloudflare Worker
// （部署好 worker 後，把下面網址換成你自己的 *.workers.dev 網址）
var CLOUD_API_BASE = 'https://jiaminglake-api.tsungkailu.workers.dev';

function resolveApiUrl(path){
  if (window.location.port === '8000') {
    return path;
  }
  return CLOUD_API_BASE + path;
}

// 背景同步失敗時的提示（畫面上已經套用了本地變更，這裡只是告知「還沒真的存進雲端」）
function showSyncErrorToast(message){
  var toast = document.createElement('div');
  toast.className = 'sync-error-toast';
  toast.textContent = '⚠️ ' + message;
  var closeBtn = document.createElement('button');
  closeBtn.textContent = '✕';
  closeBtn.setAttribute('aria-label', '關閉提示');
  closeBtn.addEventListener('click', function(){ toast.remove(); });
  toast.appendChild(closeBtn);
  document.body.appendChild(toast);
  setTimeout(function(){ toast.remove(); }, 8000);
}

// =====================================================================
// BOOT
// =====================================================================
(function boot(){
  if(typeof WAYPOINT_DATA === 'undefined'){
    document.body.innerHTML =
      "<p style='padding:20px;color:red'>找不到 waypoint-data.js，請確認檔案與 jiaminglake.html 在同一資料夾，並執行 node build.js。</p>";
    return;
  }

  var data = WAYPOINT_DATA;
  var meta = data.meta;

  dayColors        = meta.dayColors;
  dayEmoji         = meta.dayEmoji;
  dayNames         = meta.dayNames;
  TOTAL_KM         = meta.totalKm;
  SEGMENTS         = data.gpsSegments  || [];
  PROFILE_DATA     = data.profileData  || [];
  SUPPLEMENT_LINES = data.supplementLines || [];

  // Build flat WAYPOINTS array and WAYPOINT_PHOTOS lookup
  data.waypoints.forEach(function(wp){
    WAYPOINTS.push({
      name:        wp.name,
      day:         wp.day,
      order:       wp.order  || 0,
      date:        wp.date   || '',
      time:        wp.time,
      km:          wp.km,
      ele:         wp.elevation,
      lat:         wp.lat,
      lng:         wp.lng,
      profile_km:  wp.profile_km,
      profile_ele: wp.profile_ele,
      desc:        wp.desc,
      spur:        wp.spur        || false,
      spurReturn:  wp.spurReturn  || false
    });
    WAYPOINT_PHOTOS[wp.order] = (wp.photos || []).map(function(p){
      // _realSrc：這張照片在 repo 裡實際的檔案路徑，用來識別「編輯/刪除哪一張」。
      // 剛上傳、還在背景同步中的照片，_realSrc 會是 null，代表還不能編輯/刪除。
      return { src: p.src || '', title: p.title || '', body: p.body || '', _realSrc: p.src || '' };
    });
  });

  // Sort WAYPOINTS chronologically by day and order
  WAYPOINTS.sort(function(a, b){
    var di = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
    return di !== 0 ? di : (a.order || 0) - (b.order || 0);
  });

  // Boot
  initMap();
  initPhotoModal();
  buildWaypointList();
  initTabs();
  initMobileDrawer();
})();

// =====================================================================
// MAP
// =====================================================================
function initMap(){
  map = L.map('map', {zoomControl: true}).setView([23.265, 121.010], 12);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '© OpenStreetMap contributors'
  }).addTo(map);

  // ── GPS 實際軌跡（上/下坡雙色）──────────────────────────────────────
  SEGMENTS.forEach(function(seg){
    var dEle  = seg.ee - seg.es;
    var color = dEle >= 0 ? '#c0392b' : '#1565c0';
    L.polyline(seg.c, {color: color, weight: 4, opacity: 0.88})
      .bindPopup(
        '<b>' + seg.d + ' 路段</b><br>' +
        '起點：' + seg.es + 'm　終點：' + seg.ee + 'm<br>' +
        '高差：<b>' + (dEle >= 0 ? '+' : '') + dEle + 'm</b><br>' +
        '<span style="color:' + color + ';font-weight:700">' +
        (dEle >= 0 ? '▲ 上坡' : '▼ 下坡') + '</span>'
      )
      .addTo(map);
  });

  // ── 補線（無 GPS 覆蓋的路段）──────────────────────────────────────
  SUPPLEMENT_LINES.forEach(function(line){
    var color   = dayColors[line.day] || '#888';
    var options = {
      color:   color,
      weight:  3,
      opacity: 0.85
    };
    if(line.dashed){
      options.dashArray = '8, 6';
      options.weight    = 2.5;
    }
    var popup = line.label
      ? '<b>' + line.label + '</b><br><span style="color:#888;font-size:.85em">標記點連線（無 GPS 軌跡）</span>'
      : '標記點連線（無 GPS 軌跡）';
    L.polyline(line.coords, options).bindPopup(popup).addTo(map);
  });

  // ── 地標標記 ─────────────────────────────────────────────────────
  WAYPOINTS.forEach(function(wp){
    if (wp.lat === null || wp.lng === null || wp.lat === undefined || wp.lng === undefined) {
      return;
    }
    var color = dayColors[wp.day];
    var icon  = L.divIcon({
      className: '',
      html:
        "<div style='width:28px;height:28px;border-radius:50%;background:" + color +
        ";border:2px solid #fff;display:flex;align-items:center;justify-content:center;" +
        "color:#fff;font-size:.6rem;font-weight:700;box-shadow:0 2px 6px rgba(0,0,0,.4)'>" +
        wp.day + '</div>',
      iconSize: [28, 28], iconAnchor: [14, 14], popupAnchor: [0, -16]
    });
    var m = L.marker([wp.lat, wp.lng], {icon: icon, draggable: true}).addTo(map);
    (function(wp, marker){
      marker.on('click', function(){
        var onElevation = document.querySelector('[data-tab="elevation"]').classList.contains('active');
        if(!onElevation){ openPhotoModal(wp); }
        toggleChartMarker(wp);
      });
      
      marker.on('dragend', function(event){
        var position = event.target.getLatLng();
        var newLat = position.lat;
        var newLng = position.lng;
        
        // 儲存目前地圖中心點與縮放大小，以便重載後恢復
        sessionStorage.setItem('mapCenter', JSON.stringify(map.getCenter()));
        sessionStorage.setItem('mapZoom', map.getZoom());
        
        updateWaypointCoords(wp.name, wp.order, newLat, newLng);
      });
    })(wp, m);
  });

  // Fix Leaflet popup close button
  map.on('popupopen', function(){
    document.querySelectorAll('.leaflet-popup-close-button').forEach(function(btn){
      btn.removeAttribute('href');
      btn.style.cursor = 'pointer';
    });
  });

  // ── 恢復地圖定位或自動縮放至 GPS 軌跡範圍 ──────────────────────────
  var savedCenter = sessionStorage.getItem('mapCenter');
  var savedZoom   = sessionStorage.getItem('mapZoom');
  if(savedCenter && savedZoom){
    var center = JSON.parse(savedCenter);
    map.setView([center.lat, center.lng], parseInt(savedZoom));
    sessionStorage.removeItem('mapCenter');
    sessionStorage.removeItem('mapZoom');
  } else if(SEGMENTS.length > 0){
    var allLats = SEGMENTS.reduce(function(a,s){ return a.concat(s.c.map(function(p){ return p[0]; })); }, []);
    var allLngs = SEGMENTS.reduce(function(a,s){ return a.concat(s.c.map(function(p){ return p[1]; })); }, []);
    map.fitBounds([
      [Math.min.apply(null, allLats), Math.min.apply(null, allLngs)],
      [Math.max.apply(null, allLats), Math.max.apply(null, allLngs)]
    ], {padding: [40, 40]});
  }
}

// =====================================================================
// ELEVATION CHART
// =====================================================================
function buildChart(){
  if(chartBuilt) return;
  chartBuilt = true;
  var ctx = document.getElementById('elev-chart').getContext('2d');
  elevChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels:   PROFILE_DATA.map(function(p){ return p[0]; }),
      datasets: [{
        label:           '海拔',
        data:            PROFILE_DATA.map(function(p){ return p[1]; }),
        fill:            true,
        backgroundColor: 'rgba(45,90,61,.15)',
        borderColor:     '#2d5a3d',
        borderWidth:     1.5,
        pointRadius:     0,
        tension:         .3
      }]
    },
    options: {
      responsive:          true,
      maintainAspectRatio: false,
      animation:           {duration: 400},
      plugins: {
        legend:  {display: false},
        tooltip: {
          mode: 'index', intersect: false,
          callbacks: {
            title: function(i){ return i[0].parsed.x.toFixed(2) + 'km'; },
            label: function(c){ return ' ' + c.parsed.y.toFixed(0) + 'm'; }
          }
        }
      },
      scales: {
        x: {
          type: 'linear', min: 0, max: TOTAL_KM,
          ticks: {maxTicksLimit: 8, font: {size: 10}, callback: function(v){ return v.toFixed(0) + 'k'; }},
          title: {display: true, text: '距離（km）', font: {size: 10}}
        },
        y: {
          ticks: {font: {size: 10}, callback: function(v){ return v + 'm'; }},
          title: {display: true, text: '海拔（m）', font: {size: 10}}
        }
      }
    }
  });
}

function kmToPixel(km){
  if(!elevChart) return null;
  return elevChart.scales.x.getPixelForValue(km);
}
function eleToPixel(ele){
  if(!elevChart) return null;
  return elevChart.scales.y.getPixelForValue(ele);
}

function redrawOverlay(){
  var svg = document.getElementById('chart-overlay');
  while(svg.firstChild) svg.removeChild(svg.firstChild);
  if(!elevChart || !chartBuilt) return;

  var ca = elevChart.chartArea;
  activeMarkers.forEach(function(item){
    var wp    = item.wp;
    var color = dayColors[wp.day];
    var x     = kmToPixel(wp.profile_km);
    var y     = eleToPixel(wp.profile_ele);
    if(x == null) return;

    // Vertical dashed line
    var line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
    line.setAttribute('x1', x);    line.setAttribute('y1', ca.top);
    line.setAttribute('x2', x);    line.setAttribute('y2', ca.bottom);
    line.setAttribute('stroke', color);
    line.setAttribute('stroke-width', '1.5');
    line.setAttribute('stroke-dasharray', '4,3');
    line.setAttribute('opacity', '0.85');
    svg.appendChild(line);

    // Dot on curve
    if(y != null){
      var circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      circle.setAttribute('cx', x);  circle.setAttribute('cy', y);
      circle.setAttribute('r', '5');
      circle.setAttribute('fill', color);
      circle.setAttribute('stroke', '#fff');
      circle.setAttribute('stroke-width', '2');
      svg.appendChild(circle);
    }

    // Name label
    var text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
    text.setAttribute('x', x);     text.setAttribute('y', ca.top - 6);
    text.setAttribute('text-anchor', 'middle');
    text.setAttribute('font-size', '9');
    text.setAttribute('font-family', 'sans-serif');
    text.setAttribute('font-weight', '700');
    text.setAttribute('fill', color);
    text.textContent = wp.name;
    svg.appendChild(text);
  });
}

function toggleChartMarker(wp){
  buildChart();
  var onElevation = document.querySelector('[data-tab="elevation"]').classList.contains('active');
  if(onElevation){
    var idx = activeMarkers.findIndex(function(m){ return m.wp.name === wp.name; });
    if(idx >= 0){ activeMarkers.splice(idx, 1); }
    else         { activeMarkers = [{wp: wp}]; }
  } else {
    var idx = activeMarkers.findIndex(function(m){ return m.wp.name === wp.name; });
    if(idx >= 0){ activeMarkers.splice(idx, 1); }
    else         { activeMarkers.push({wp: wp}); }
  }
  updateElevHint();
  updateElevDetail();
  requestAnimationFrame(redrawOverlay);
}

// 高度剖面彈窗的上一點／下一點導覽：直接切換成單一標記點 (取代原本的多選標記)
function selectElevWaypoint(wp){
  buildChart();
  activeMarkers = [{wp: wp}];
  updateElevHint();
  updateElevDetail();
  requestAnimationFrame(redrawOverlay);
}

function updateElevHint(){
  var hint = document.getElementById('chart-hint');
  if(activeMarkers.length > 0){
    hint.textContent = '📍 ' + activeMarkers.map(function(m){ return m.wp.name; }).join('、');
    hint.style.color = '#333';
  } else {
    hint.textContent = '點擊地標可標記於此';
    hint.style.color = 'var(--muted)';
  }
}

function updateElevDetail(){
  var detail = document.getElementById('elev-wp-detail');
  var empty  = document.getElementById('elev-wp-empty');
  if(activeMarkers.length > 0){
    var sel   = activeMarkers[activeMarkers.length - 1].wp;
    var color = dayColors[sel.day];
    document.getElementById('elev-wp-dot').style.background = color;
    document.getElementById('elev-wp-dot').textContent = sel.day;
    document.getElementById('elev-wp-name').textContent =
      (dayEmoji[sel.day] || '') + ' ' + sel.name;
    document.getElementById('elev-wp-meta').innerHTML =
      '<span>⛰ ' + sel.ele + '</span>' +
      '<span>📏 ' + sel.km + '</span>' +
      '<span>⏰ ' + sel.time + '</span>';
    document.getElementById('elev-wp-desc').textContent = sel.desc;
    detail.style.display = 'block';
    empty.style.display  = 'none';

    var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === sel.order; });
    var prevBtn = document.getElementById('elev-nav-prev');
    var nextBtn = document.getElementById('elev-nav-next');
    prevBtn.disabled = (currIdx <= 0);
    nextBtn.disabled = (currIdx < 0 || currIdx >= WAYPOINTS.length - 1);

    loadElevPhotoSection(sel);
  } else {
    detail.style.display = 'none';
    empty.style.display  = 'flex';
  }
}

// 高度剖面彈窗自己的照片區塊 (與照片彈窗各自獨立的瀏覽狀態)
function showEmptyElevPhoto(){
  document.getElementById('elev-photo-delete-btn').style.display = 'none';
  document.getElementById('elev-photo-edit-btn').style.display   = 'none';
  document.getElementById('elev-photo-img').src = '';
  document.getElementById('elev-photo-img').alt = '暫無照片';
  document.getElementById('elev-photo-dots').innerHTML = '';
  document.getElementById('elev-photo-title').textContent = '尚未新增照片';
  document.getElementById('elev-photo-body').textContent  = '請點擊左上角按鈕新增照片至此地標。';
  document.getElementById('elev-photo-prev').style.display = 'none';
  document.getElementById('elev-photo-next').style.display = 'none';
}

function loadElevPhotoSection(wp){
  var photos = WAYPOINT_PHOTOS[wp.order] || [];
  currentElevPhotos        = photos;
  currentElevPhotoIdx      = 0;
  currentElevWaypointName  = wp.name;
  currentElevWaypointOrder = wp.order;

  if(photos.length === 0){
    showEmptyElevPhoto();
  } else {
    renderElevPhoto();
    document.getElementById('elev-photo-prev').style.display = photos.length > 1 ? 'flex' : 'none';
    document.getElementById('elev-photo-next').style.display = photos.length > 1 ? 'flex' : 'none';
  }
}

function renderElevPhoto(){
  var p = currentElevPhotos[currentElevPhotoIdx];
  document.getElementById('elev-photo-delete-btn').style.display = 'flex';
  document.getElementById('elev-photo-edit-btn').style.display   = 'flex';
  document.getElementById('elev-photo-img').src = p.src;
  document.getElementById('elev-photo-img').alt = p.title || '';
  document.getElementById('elev-photo-title').textContent = p.title || '';
  document.getElementById('elev-photo-body').textContent  = p.body  || '';

  var dotsEl = document.getElementById('elev-photo-dots');
  dotsEl.innerHTML = '';
  currentElevPhotos.forEach(function(_, idx){
    var dot = document.createElement('div');
    dot.className = 'photo-dot' + (idx === currentElevPhotoIdx ? ' active' : '');
    dot.addEventListener('click', function(){ currentElevPhotoIdx = idx; renderElevPhoto(); });
    dotsEl.appendChild(dot);
  });
}

window.addEventListener('resize', function(){
  requestAnimationFrame(redrawOverlay);
});

// =====================================================================
// WAYPOINT SIDEBAR LIST
// =====================================================================
function buildWaypointList(){
  var wpList = document.getElementById('wp-list');

  DAY_ORDER.forEach(function(day){
    var dayWps = WAYPOINTS
      .filter(function(wp){ return wp.day === day; })
      .sort(function(a, b){ return (a.order || 0) - (b.order || 0); });

    if(!dayWps.length) return;

    var group = document.createElement('div');
    group.className = 'day-group';

    var label = document.createElement('div');
    label.className = 'day-label';
    label.style.background = dayColors[day];
    label.textContent = dayNames[day] || day;
    group.appendChild(label);

    dayWps.forEach(function(wp, i){
      var card = document.createElement('div');
      card.className = 'wp-card';

      // 支線點加上視覺標示
      var spurBadge = wp.spur
        ? "<span style='font-size:.6rem;background:#e67e22;color:#fff;border-radius:3px;padding:1px 4px;margin-left:4px'>支線</span>"
        : '';

      var dot = document.createElement('div');
      dot.className = 'wp-dot';
      dot.style.background = dayColors[day];
      dot.textContent = wp.order || (i + 1);

      var info = document.createElement('div');
      info.className = 'wp-info';
      info.innerHTML =
        "<div class='wp-name'>" + wp.name + spurBadge + '</div>' +
        "<div class='wp-meta'>" +
          '<span>⛰ ' + wp.ele  + '</span>' +
          '<span>📏 ' + wp.km   + '</span>' +
          '<span>⏰ ' + wp.time + '</span>' +
        '</div>' +
        "<div class='wp-desc'>" + wp.desc + '</div>';

      card.appendChild(dot);
      card.appendChild(info);

      card.addEventListener('click', (function(wp, card){
        return function(){
          if(activeCard) activeCard.classList.remove('active');
          card.classList.add('active');
          activeCard = card;
          if (wp.lat !== null && wp.lng !== null && wp.lat !== undefined && wp.lng !== undefined) {
            map.setView([wp.lat, wp.lng], 15, {animate: true});
          }
          var onElevation = document.querySelector('[data-tab="elevation"]').classList.contains('active');
          if(!onElevation){ openPhotoModal(wp); }
          toggleChartMarker(wp);
          if(window.innerWidth < 768 && !onElevation){
            setMobileDrawerState('closed');
          }
        };
      })(wp, card));

      group.appendChild(card);
    });

    wpList.appendChild(group);
  });
}

// =====================================================================
// PHOTO MODAL
// =====================================================================
// 將圖片檔案壓縮並轉換為 WebP 格式的 Base64 (寬或高最大 1200px，畫質 0.82)
function compressImageToWebp(file, callback){
  var reader = new FileReader();
  reader.onload = function(e){
    compressDataUrlToWebp(e.target.result, callback);
  };
  reader.readAsDataURL(file);
}

// 與上面共用的核心壓縮邏輯，輸入直接是圖片的 data URL (例如從雲端硬碟下載後取得的圖片)
function compressDataUrlToWebp(dataUrl, callback){
  var img = new Image();
  img.onload = function(){
    var maxDim = 1200;
    var width = img.width;
    var height = img.height;
    if(width > maxDim || height > maxDim){
      if(width > height){
        height = Math.round((height * maxDim) / width);
        width = maxDim;
      } else {
        width = Math.round((width * maxDim) / height);
        height = maxDim;
      }
    }

    var canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0, width, height);

    callback(canvas.toDataURL('image/webp', 0.82));
  };
  img.src = dataUrl;
}

// 請伺服器下載一個公開的 Google Drive 檔案分享連結，回傳圖片的 data URL。
// Worker 會直接把圖片位元組串流回來（成功時 Content-Type 是 image/*），
// 失敗時才會是一段 JSON 錯誤訊息。
function fetchDriveImageAsDataUrl(driveUrl, onSuccess, onError){
  var apiUrl = resolveApiUrl('/api/fetch-drive-image');
  fetch(apiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: driveUrl })
  })
  .then(function(res){
    var contentType = res.headers.get('content-type') || '';
    if (!res.ok || contentType.indexOf('application/json') === 0) {
      return res.json().then(function(errRes){
        throw new Error(errRes.error || ('HTTP ' + res.status));
      });
    }
    return res.blob();
  })
  .then(function(blob){
    var reader = new FileReader();
    reader.onload = function(e){ onSuccess(e.target.result); };
    reader.onerror = function(){ onError('讀取圖片資料失敗'); };
    reader.readAsDataURL(blob);
  })
  .catch(function(err){ onError(err.message || String(err)); });
}

function resetUploadForm(){
  document.getElementById('upload-image').value = '';
  document.getElementById('upload-drive-url').value = '';
  document.getElementById('upload-title').value = '';
  document.getElementById('upload-body').value = '';
  document.getElementById('upload-status').textContent = '';
  document.getElementById('upload-status').className = 'upload-status';
}

function initPhotoModal(){
  var photoModal = document.getElementById('photo-modal');
  var uploadModal = document.getElementById('upload-modal');

  // 主彈窗關閉按鈕
  document.getElementById('photo-modal-close').addEventListener('click', function(){
    photoModal.classList.remove('open');
  });
  photoModal.addEventListener('click', function(e){
    if(e.target === photoModal) photoModal.classList.remove('open');
  });

  // 新增照片彈窗控制
  var btnOpenUpload = document.getElementById('btn-open-upload-modal');
  if (btnOpenUpload) {
    btnOpenUpload.addEventListener('click', function(){
      activePhotoSource = 'modal';
      resetUploadForm();
      uploadModal.classList.add('open');
    });
  }
  var elevPhotoAddBtn = document.getElementById('elev-photo-add-btn');
  if (elevPhotoAddBtn) {
    elevPhotoAddBtn.addEventListener('click', function(){
      activePhotoSource = 'elev';
      resetUploadForm();
      uploadModal.classList.add('open');
    });
  }
  var btnCloseUpload = document.getElementById('upload-modal-close');
  if (btnCloseUpload) {
    btnCloseUpload.addEventListener('click', function(){
      uploadModal.classList.remove('open');
    });
  }
  uploadModal.addEventListener('click', function(e){
    if(e.target === uploadModal) uploadModal.classList.remove('open');
  });

  // 編輯地標彈窗控制
  var editModal = document.getElementById('edit-modal');
  var btnOpenEdit = document.getElementById('btn-open-edit-modal');
  if (btnOpenEdit) {
    btnOpenEdit.addEventListener('click', function(){
      var wp = WAYPOINTS.find(function(w){ return w.order === currentWaypointOrder; });
      if(!wp) return;
      document.getElementById('edit-name').value      = wp.name;
      document.getElementById('edit-day').value       = wp.day;
      document.getElementById('edit-time').value      = wp.time;
      document.getElementById('edit-km').value        = wp.km;
      document.getElementById('edit-elevation').value = wp.ele;
      document.getElementById('edit-desc').value      = wp.desc;
      document.getElementById('edit-status').textContent = '';
      document.getElementById('edit-status').className  = 'upload-status';
      editModal.classList.add('open');
    });
  }
  var btnCloseEdit = document.getElementById('edit-modal-close');
  if (btnCloseEdit) {
    btnCloseEdit.addEventListener('click', function(){
      editModal.classList.remove('open');
    });
  }
  editModal.addEventListener('click', function(e){
    if(e.target === editModal) editModal.classList.remove('open');
  });

  // 編輯照片彈窗控制
  var editPhotoModal = document.getElementById('edit-photo-modal');
  function openEditPhotoModal(source){
    activePhotoSource = source;
    var photo = getActivePhotos()[getActivePhotoIdx()];
    if(!photo) return;
    if(!photo._realSrc){
      alert('這張照片還在同步到 GitHub 中，請稍等一下再編輯。');
      return;
    }
    editingPhotoSrc = photo._realSrc;
    document.getElementById('edit-photo-image').value = '';
    document.getElementById('edit-photo-drive-url').value = '';
    document.getElementById('edit-photo-title').value = photo.title || '';
    document.getElementById('edit-photo-body').value  = photo.body  || '';
    document.getElementById('edit-photo-status').textContent = '';
    document.getElementById('edit-photo-status').className  = 'upload-status';
    editPhotoModal.classList.add('open');
  }
  var btnOpenEditPhoto = document.getElementById('photo-modal-edit-btn');
  if (btnOpenEditPhoto) {
    btnOpenEditPhoto.addEventListener('click', function(){ openEditPhotoModal('modal'); });
  }
  var elevPhotoEditBtn = document.getElementById('elev-photo-edit-btn');
  if (elevPhotoEditBtn) {
    elevPhotoEditBtn.addEventListener('click', function(){ openEditPhotoModal('elev'); });
  }
  var btnCloseEditPhoto = document.getElementById('edit-photo-modal-close');
  if (btnCloseEditPhoto) {
    btnCloseEditPhoto.addEventListener('click', function(){
      editPhotoModal.classList.remove('open');
    });
  }
  editPhotoModal.addEventListener('click', function(e){
    if(e.target === editPhotoModal) editPhotoModal.classList.remove('open');
  });

  // 上一點 / 下一點地標導覽
  document.getElementById('wp-nav-prev').addEventListener('click', function(){
    var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === currentWaypointOrder; });
    if(currIdx > 0){
      openPhotoModal(WAYPOINTS[currIdx - 1]);
    }
  });
  document.getElementById('wp-nav-next').addEventListener('click', function(){
    var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === currentWaypointOrder; });
    if(currIdx < WAYPOINTS.length - 1){
      openPhotoModal(WAYPOINTS[currIdx + 1]);
    }
  });

  // 高度剖面彈窗的上一點 / 下一點地標導覽 (與照片彈窗各自獨立)
  document.getElementById('elev-nav-prev').addEventListener('click', function(){
    var sel = activeMarkers.length > 0 ? activeMarkers[activeMarkers.length - 1].wp : null;
    if(!sel) return;
    var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === sel.order; });
    if(currIdx > 0){
      selectElevWaypoint(WAYPOINTS[currIdx - 1]);
    }
  });
  document.getElementById('elev-nav-next').addEventListener('click', function(){
    var sel = activeMarkers.length > 0 ? activeMarkers[activeMarkers.length - 1].wp : null;
    if(!sel) return;
    var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === sel.order; });
    if(currIdx >= 0 && currIdx < WAYPOINTS.length - 1){
      selectElevWaypoint(WAYPOINTS[currIdx + 1]);
    }
  });

  // 照片切換
  document.getElementById('photo-prev').addEventListener('click', function(){
    if(currentPhotos.length < 2) return;
    currentPhotoIdx = (currentPhotoIdx - 1 + currentPhotos.length) % currentPhotos.length;
    renderPhoto();
  });
  document.getElementById('photo-next').addEventListener('click', function(){
    if(currentPhotos.length < 2) return;
    currentPhotoIdx = (currentPhotoIdx + 1) % currentPhotos.length;
    renderPhoto();
  });
  document.getElementById('elev-photo-prev').addEventListener('click', function(){
    if(currentElevPhotos.length < 2) return;
    currentElevPhotoIdx = (currentElevPhotoIdx - 1 + currentElevPhotos.length) % currentElevPhotos.length;
    renderElevPhoto();
  });
  document.getElementById('elev-photo-next').addEventListener('click', function(){
    if(currentElevPhotos.length < 2) return;
    currentElevPhotoIdx = (currentElevPhotoIdx + 1) % currentElevPhotos.length;
    renderElevPhoto();
  });
  document.addEventListener('keydown', function(e){
    if(uploadModal.classList.contains('open')) {
      if(e.key === 'Escape') uploadModal.classList.remove('open');
      return;
    }
    if(editModal.classList.contains('open')) {
      if(e.key === 'Escape') editModal.classList.remove('open');
      return;
    }
    if(editPhotoModal.classList.contains('open')) {
      if(e.key === 'Escape') editPhotoModal.classList.remove('open');
      return;
    }
    if(!photoModal.classList.contains('open')) return;
    if(e.key === 'ArrowLeft')  document.getElementById('photo-prev').click();
    if(e.key === 'ArrowRight') document.getElementById('photo-next').click();
    if(e.key === 'Escape')     photoModal.classList.remove('open');
  });

  // ── 照片上傳與 Canvas WebP 壓縮邏輯 ──────────────────────────────
  var btnSubmit = document.getElementById('upload-submit');
  var fileInput = document.getElementById('upload-image');
  var statusEl  = document.getElementById('upload-status');

  if (btnSubmit) {
    btnSubmit.addEventListener('click', function(){
      var file     = fileInput.files[0];
      var driveUrl = document.getElementById('upload-drive-url').value.trim();

      if(!file && !driveUrl){
        statusEl.textContent = '❌ 請選擇一張照片，或貼上 Google Drive 分享連結';
        statusEl.className = 'upload-status error';
        return;
      }
      if(!getActiveWaypointName()){
        statusEl.textContent = '❌ 無法辨識當前地標';
        statusEl.className = 'upload-status error';
        return;
      }

      function proceedWithDataUrl(dataUrl){
        statusEl.textContent = '⏳ 正在壓縮圖片中...';
        statusEl.className = 'upload-status';

        compressDataUrlToWebp(dataUrl, function(webpBase64){
          var titleVal = document.getElementById('upload-title').value.trim();
          var bodyVal  = document.getElementById('upload-body').value.trim();
          var waypointName  = getActiveWaypointName();
          var waypointOrder = getActiveWaypointOrder();

          // ── Optimistic UI：不等雲端同步，先把照片加進本地資料立刻顯示 ──
          var newPhoto = { src: webpBase64, title: titleVal, body: bodyVal, _realSrc: null };
          if (!WAYPOINT_PHOTOS[waypointOrder]) WAYPOINT_PHOTOS[waypointOrder] = [];
          WAYPOINT_PHOTOS[waypointOrder].push(newPhoto);
          refreshActivePhotoView(WAYPOINT_PHOTOS[waypointOrder].length - 1);

          statusEl.textContent = '✅ 已顯示在畫面上！背景同步到 GitHub 中...';
          statusEl.className = 'upload-status success';
          setTimeout(function(){
            uploadModal.classList.remove('open');
          }, 600);

          var uploadUrl = resolveApiUrl('/api/upload');

          fetch(uploadUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              waypointName: waypointName,
              waypointOrder: waypointOrder,
              title: titleVal,
              body: bodyVal,
              image: webpBase64
            })
          })
          .then(function(res){ return res.json(); })
          .then(function(res){
            if(res.success){
              newPhoto._realSrc = res.src;
            } else {
              showSyncErrorToast('照片同步到 GitHub 失敗（畫面上仍看得到，但重新整理後會消失）: ' + res.error);
            }
          })
          .catch(function(err){
            showSyncErrorToast('照片同步到 GitHub 失敗（畫面上仍看得到，但重新整理後會消失）: ' + err);
          });
        });
      }

      if(file){
        var reader = new FileReader();
        reader.onload = function(e){ proceedWithDataUrl(e.target.result); };
        reader.readAsDataURL(file);
        return;
      }

      statusEl.textContent = '⏳ 正在從 Google Drive 下載圖片...';
      statusEl.className = 'upload-status';
      fetchDriveImageAsDataUrl(driveUrl, proceedWithDataUrl, function(err){
        statusEl.textContent = '❌ 下載失敗: ' + err;
        statusEl.className = 'upload-status error';
      });
    });
  }

  // ── 照片刪除邏輯 (照片彈窗、高度剖面照片區共用) ────────────────────
  function deleteActivePhoto(){
    var photos = getActivePhotos();
    var idx = getActivePhotoIdx();
    var photo = photos[idx];
    if (!photo) return;

    if (!photo._realSrc) {
      alert('這張照片還在同步到 GitHub 中，請稍等一下再刪除。');
      return;
    }

    var isConfirmed = confirm("確定要刪除這張照片嗎？\n這將會從檔案庫中永久刪除此照片且無法復原！");
    if (!isConfirmed) return;

    // ── Optimistic UI：不等雲端同步，先從畫面上移除 ──
    var waypointName  = getActiveWaypointName();
    var waypointOrder = getActiveWaypointOrder();
    var photoSrc = photo._realSrc;
    photos.splice(idx, 1);
    refreshActivePhotoView(idx);

    var deleteUrl = resolveApiUrl('/api/delete-photo');

    fetch(deleteUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        waypointName: waypointName,
        waypointOrder: waypointOrder,
        photoSrc: photoSrc
      })
    })
    .then(function(res){ return res.json(); })
    .then(function(res){
      if(!res.success){
        showSyncErrorToast('刪除同步到 GitHub 失敗: ' + res.error);
      }
    })
    .catch(function(err){
      showSyncErrorToast('刪除同步到 GitHub 失敗: ' + err);
    });
  }

  var btnDelete = document.getElementById('photo-modal-delete-btn');
  if (btnDelete) {
    btnDelete.addEventListener('click', function(){
      activePhotoSource = 'modal';
      deleteActivePhoto();
    });
  }
  var elevPhotoDeleteBtn = document.getElementById('elev-photo-delete-btn');
  if (elevPhotoDeleteBtn) {
    elevPhotoDeleteBtn.addEventListener('click', function(){
      activePhotoSource = 'elev';
      deleteActivePhoto();
    });
  }

  // ── 地標編輯邏輯 ─────────────────────────────────────────────────
  var btnEditSubmit = document.getElementById('edit-submit');
  if (btnEditSubmit) {
    btnEditSubmit.addEventListener('click', function(){
      var statusEl = document.getElementById('edit-status');
      var nameVal = document.getElementById('edit-name').value.trim();
      var dayVal  = document.getElementById('edit-day').value;
      var timeVal = document.getElementById('edit-time').value.trim();
      var kmVal   = document.getElementById('edit-km').value.trim();
      var eleVal  = document.getElementById('edit-elevation').value.trim();
      var descVal = document.getElementById('edit-desc').value.trim();

      if(!nameVal || !timeVal || !kmVal || !eleVal){
        statusEl.textContent = '❌ 請完整填寫所有欄位';
        statusEl.className = 'upload-status error';
        return;
      }

      statusEl.textContent = '⏳ 正在儲存修改...';
      statusEl.className = 'upload-status';

      var updateUrl = resolveApiUrl('/api/update-waypoint');

      fetch(updateUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          waypointOrder: currentWaypointOrder,
          name: nameVal,
          day: dayVal,
          time: timeVal,
          km: kmVal,
          elevation: eleVal,
          desc: descVal
        })
      })
      .then(function(res){ return res.json(); })
      .then(function(res){
        if(res.success){
          statusEl.textContent = '🎉 更新成功！網頁即將重新整理...';
          statusEl.className = 'upload-status success';
          setTimeout(function(){
            window.location.reload();
          }, 1000);
        } else {
          statusEl.textContent = '❌ 更新失敗: ' + res.error;
          statusEl.className = 'upload-status error';
        }
      })
      .catch(function(err){
        statusEl.textContent = '❌ 連線伺服器失敗: ' + err;
        statusEl.className = 'upload-status error';
      });
    });
  }

  // ── 照片編輯邏輯 ─────────────────────────────────────────────────
  var btnEditPhotoSubmit = document.getElementById('edit-photo-submit');
  if (btnEditPhotoSubmit) {
    btnEditPhotoSubmit.addEventListener('click', function(){
      var statusEl   = document.getElementById('edit-photo-status');
      var fileInput  = document.getElementById('edit-photo-image');
      var driveUrl   = document.getElementById('edit-photo-drive-url').value.trim();
      var titleVal   = document.getElementById('edit-photo-title').value.trim();
      var bodyVal    = document.getElementById('edit-photo-body').value.trim();
      var file       = fileInput.files[0];

      function sendPhotoUpdate(webpBase64){
        var photos = getActivePhotos();
        var photo = photos.find(function(p){ return p._realSrc === editingPhotoSrc; });
        if(!photo) return;

        // ── Optimistic UI：不等雲端同步，先套用修改立刻顯示 ──
        photo.title = titleVal;
        photo.body  = bodyVal;
        if (webpBase64) photo.src = webpBase64;
        refreshActivePhotoView(photos.indexOf(photo));

        statusEl.textContent = '✅ 已套用修改！背景同步到 GitHub 中...';
        statusEl.className = 'upload-status success';
        setTimeout(function(){
          editPhotoModal.classList.remove('open');
        }, 600);

        var updateUrl = resolveApiUrl('/api/update-photo');

        var payload = {
          waypointName: getActiveWaypointName(),
          waypointOrder: getActiveWaypointOrder(),
          photoSrc: editingPhotoSrc,
          title: titleVal,
          body: bodyVal
        };
        if (webpBase64) payload.image = webpBase64;

        fetch(updateUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        })
        .then(function(res){ return res.json(); })
        .then(function(res){
          if(!res.success){
            showSyncErrorToast('照片編輯同步到 GitHub 失敗: ' + res.error);
          }
        })
        .catch(function(err){
          showSyncErrorToast('照片編輯同步到 GitHub 失敗: ' + err);
        });
      }

      if(file){
        var reader = new FileReader();
        reader.onload = function(e){
          statusEl.textContent = '⏳ 正在壓縮圖片中...';
          statusEl.className = 'upload-status';
          compressDataUrlToWebp(e.target.result, sendPhotoUpdate);
        };
        reader.readAsDataURL(file);
        return;
      }

      if(driveUrl){
        statusEl.textContent = '⏳ 正在從 Google Drive 下載圖片...';
        statusEl.className = 'upload-status';
        fetchDriveImageAsDataUrl(driveUrl, function(dataUrl){
          statusEl.textContent = '⏳ 正在壓縮圖片中...';
          compressDataUrlToWebp(dataUrl, sendPhotoUpdate);
        }, function(err){
          statusEl.textContent = '❌ 下載失敗: ' + err;
          statusEl.className = 'upload-status error';
        });
        return;
      }

      sendPhotoUpdate(null);
    });
  }
}

function openPhotoModal(wp){
  var photos = WAYPOINT_PHOTOS[wp.order] || [];
  currentPhotos   = photos;
  currentPhotoIdx = 0;
  currentWaypointName = wp.name;
  currentWaypointOrder = wp.order;

  resetUploadForm();

  // 重設置頂滾動條
  var scrollEl = document.getElementById('photo-modal-scrollable');
  if (scrollEl) scrollEl.scrollTop = 0;

  var photoModal = document.getElementById('photo-modal');
  
  // 大標題與副標題分開
  document.getElementById('photo-modal-title').textContent = wp.day + '-' + wp.order + ' ' + wp.name;
  document.getElementById('photo-modal-meta').textContent = '📏 ' + wp.km + '　⏰ ' + wp.time + '　⛰ ' + wp.ele;
  document.getElementById('photo-modal-desc').textContent = wp.desc || '';

  // 上一點 / 下一點導覽按鈕啟用狀態
  var currIdx = WAYPOINTS.findIndex(function(w){ return w.order === wp.order; });
  var prevBtn = document.getElementById('wp-nav-prev');
  var nextBtn = document.getElementById('wp-nav-next');
  if(prevBtn) prevBtn.disabled = (currIdx <= 0);
  if(nextBtn) nextBtn.disabled = (currIdx < 0 || currIdx >= WAYPOINTS.length - 1);

  if(photos.length === 0){
    showEmptyPhotoModal();
  } else {
    renderPhoto();
    document.getElementById('photo-prev').style.display = photos.length > 1 ? 'flex' : 'none';
    document.getElementById('photo-next').style.display = photos.length > 1 ? 'flex' : 'none';
  }
  photoModal.classList.add('open');
}

function showEmptyPhotoModal(){
  document.getElementById('photo-modal-delete-btn').style.display = 'none';
  document.getElementById('photo-modal-edit-btn').style.display   = 'none';
  document.getElementById('photo-modal-img').src        = '';
  document.getElementById('photo-modal-img').alt        = '暫無照片';
  document.getElementById('photo-modal-dots').innerHTML  = '';
  document.getElementById('photo-modal-photo-title').textContent = '尚未新增照片';
  document.getElementById('photo-modal-photo-body').textContent  = '請點擊下方按鈕新增照片至此地標。';
  document.getElementById('photo-prev').style.display = 'none';
  document.getElementById('photo-next').style.display = 'none';
}

// Optimistic UI：新增/編輯/刪除照片後，立刻用目前 WAYPOINT_PHOTOS 的內容重繪
// 當前開啟中的照片檢視區塊 (照片彈窗或高度剖面照片區)，不必等雲端同步、不必整頁重新整理
function refreshActivePhotoView(targetIdx){
  if (activePhotoSource === 'elev') {
    currentElevPhotos = WAYPOINT_PHOTOS[currentElevWaypointOrder] || [];
    if (currentElevPhotos.length === 0) { showEmptyElevPhoto(); return; }
    currentElevPhotoIdx = Math.max(0, Math.min(targetIdx, currentElevPhotos.length - 1));
    document.getElementById('elev-photo-prev').style.display = currentElevPhotos.length > 1 ? 'flex' : 'none';
    document.getElementById('elev-photo-next').style.display = currentElevPhotos.length > 1 ? 'flex' : 'none';
    renderElevPhoto();
  } else {
    currentPhotos = WAYPOINT_PHOTOS[currentWaypointOrder] || [];
    if (currentPhotos.length === 0) { showEmptyPhotoModal(); return; }
    currentPhotoIdx = Math.max(0, Math.min(targetIdx, currentPhotos.length - 1));
    document.getElementById('photo-prev').style.display = currentPhotos.length > 1 ? 'flex' : 'none';
    document.getElementById('photo-next').style.display = currentPhotos.length > 1 ? 'flex' : 'none';
    renderPhoto();
  }
}

function renderPhoto(){
  var p = currentPhotos[currentPhotoIdx];
  document.getElementById('photo-modal-delete-btn').style.display = 'flex';
  document.getElementById('photo-modal-edit-btn').style.display   = 'flex';
  document.getElementById('photo-modal-img').src   = p.src;
  document.getElementById('photo-modal-img').alt   = p.title || '';
  document.getElementById('photo-modal-photo-title').textContent = p.title || '';
  document.getElementById('photo-modal-photo-body').textContent  = p.body  || '';

  var dotsEl = document.getElementById('photo-modal-dots');
  dotsEl.innerHTML = '';
  currentPhotos.forEach(function(_, idx){
    var dot = document.createElement('div');
    dot.className = 'photo-dot' + (idx === currentPhotoIdx ? ' active' : '');
    dot.addEventListener('click', function(){ currentPhotoIdx = idx; renderPhoto(); });
    dotsEl.appendChild(dot);
  });
}

// =====================================================================
// TABS
// =====================================================================
function initTabs(){
  document.querySelectorAll('.tab-btn').forEach(function(btn){
    btn.addEventListener('click', function(){
      document.querySelectorAll('.tab-btn').forEach(function(b){ b.classList.remove('active'); });
      document.querySelectorAll('.tab-pane').forEach(function(p){ p.classList.remove('active'); });
      btn.classList.add('active');
      document.getElementById('tab-' + btn.dataset.tab).classList.add('active');
      if(btn.dataset.tab === 'elevation'){
        buildChart();
        requestAnimationFrame(redrawOverlay);
      }
    });
  });
}

// =====================================================================
// MOBILE DRAWER
// 右下角按鈕直接在「關閉 → 行程亮點全螢幕彈窗 → 高度剖面全螢幕彈窗 → 關閉」間切換
// =====================================================================
function setMobileDrawerState(state){
  var drawer = document.getElementById('side-panel');
  var toggle = document.getElementById('drawer-toggle');
  if(state === 'closed'){
    drawer.classList.remove('open');
    toggle.textContent = '📋';
    return;
  }
  drawer.classList.add('open');
  document.querySelector('.tab-btn[data-tab="' + state + '"]').click();
  toggle.textContent = (state === 'waypoints') ? '📈' : '✕';
}

function initMobileDrawer(){
  var toggle = document.getElementById('drawer-toggle');
  var drawer = document.getElementById('side-panel');
  toggle.addEventListener('click', function(){
    if(!drawer.classList.contains('open')){
      setMobileDrawerState('waypoints');
      return;
    }
    var onElevation = document.querySelector('.tab-btn[data-tab="elevation"]').classList.contains('active');
    setMobileDrawerState(onElevation ? 'closed' : 'elevation');
  });
}

// ── 更新地標座標之 API 請求 ─────────────────────────────────────────
function updateWaypointCoords(name, order, lat, lng) {
  var updateUrl = resolveApiUrl('/api/update-coords');

  fetch(updateUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      waypointName: name,
      waypointOrder: order,
      lat: lat,
      lng: lng
    })
  })
  .then(function(res){ return res.json(); })
  .then(function(res){
    if(res.success){
      console.log('Coordinates updated successfully for: ' + name);
      window.location.reload();
    } else {
      alert('❌ 更新座標失敗: ' + res.error);
    }
  })
  .catch(function(err){
    alert('❌ 連線伺服器失敗: ' + err);
  });
}
